application: boilerplate-gae-python27
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- remote_api: on
- deferred: on

libraries:
- name: webob
  version: 1.2.3
- name: webapp2
  version: 2.5.2

handlers:
- url: /.*
  script: src.app

skip_files:
- ^configure$
- ^Makefile\.local$
- ^Makefile$
- ^requirements*\.pip$
- ^app\.yaml
- ^app\.yml
- ^index\.yaml
- ^index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^build/.*
- ^db/.*
- ^xunit/.*
